/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clothing_distro;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author ASUS
 */
public class KARYAWAN extends javax.swing.JFrame {
    Connection conn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form NewJFrame
     */
    public KARYAWAN() {
        super("KARYAWAN");
        initComponents();
        jPanel1.setBackground(new java.awt.Color(0,0,204,50));
        jPanel2.setBackground(new java.awt.Color(0,0,204,50));
        jPanel4.setBackground(new java.awt.Color(0,0,204,50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        j3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        j4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        j5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        j6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        j7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        j8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        j11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        j12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        j13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        j14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        j15 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        j10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Swis721 Cn BT", 0, 36)); // NOI18N
        jButton8.setText("LOGOUT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1214, 0, -1, -1));

        jTabbedPane1.setFont(new java.awt.Font("Swis721 Cn BT", 0, 36)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(248, 300));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KODE PEMESANAN");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        j1.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j1.setPreferredSize(new java.awt.Dimension(7, 43));
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        jPanel4.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 310, -1));

        j2.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j2.setPreferredSize(new java.awt.Dimension(7, 43));
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        jPanel4.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 310, -1));

        jLabel7.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA PEMESAN");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        j3.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j3.setPreferredSize(new java.awt.Dimension(7, 43));
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        jPanel4.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 310, -1));

        jLabel8.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NO HP");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        j4.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j4.setPreferredSize(new java.awt.Dimension(7, 43));
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        jPanel4.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 310, -1));

        jLabel9.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ALAMAT");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        j5.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j5.setPreferredSize(new java.awt.Dimension(7, 43));
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });
        jPanel4.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 310, -1));

        jLabel10.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("JENIS KAIN");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        j6.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j6.setPreferredSize(new java.awt.Dimension(7, 43));
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });
        jPanel4.add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 310, -1));

        jLabel11.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("WARNA");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        j7.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j7.setPreferredSize(new java.awt.Dimension(7, 43));
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });
        jPanel4.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 310, -1));

        jLabel12.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("JENIS SABLON");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        j8.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j8.setPreferredSize(new java.awt.Dimension(7, 43));
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });
        jPanel4.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 310, -1));

        jLabel13.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("JUMLAH");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TANGGAL PENGAMBILAN");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jDateChooser1.setPreferredSize(new java.awt.Dimension(7, 43));
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 310, -1));

        jButton9.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jButton9.setText("KERANJANG");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, -1));

        jButton10.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jButton10.setText("CETAK BUKTI PEMESANAN");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 410, -1));

        jLabel17.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("S");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        j11.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j11.setPreferredSize(new java.awt.Dimension(7, 43));
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });
        jPanel4.add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 130, -1));

        jLabel18.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("M");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        j12.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j12.setPreferredSize(new java.awt.Dimension(7, 43));
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });
        jPanel4.add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 130, -1));

        jLabel19.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("L");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        j13.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j13.setPreferredSize(new java.awt.Dimension(7, 43));
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });
        jPanel4.add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 130, -1));

        jLabel20.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("XL");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        j14.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j14.setPreferredSize(new java.awt.Dimension(7, 43));
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });
        jPanel4.add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 130, -1));

        jLabel21.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("XXL");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        j15.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j15.setPreferredSize(new java.awt.Dimension(7, 43));
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });
        jPanel4.add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 130, -1));

        jLabel22.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("LAIN");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jLabel23.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("HARGA");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jTextField14.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        jTextField14.setPreferredSize(new java.awt.Dimension(7, 43));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 310, -1));

        jButton13.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jButton13.setText("HARGA");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, -1, -1));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 430, 420));

        jLabel24.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SIZE");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jButton12.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jButton12.setText("PESANAN SELESAI");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        j10.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        j10.setPreferredSize(new java.awt.Dimension(7, 43));
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });
        jPanel4.add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 130, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 1370, 660));

        jTabbedPane1.addTab("PEMESANAN", jPanel1);

        jTable1.setFont(new java.awt.Font("Swis721 Cn BT", 0, 36)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_BARANG", "NAMA_BARANG", "HARGA", "STOK"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane2.setViewportView(jTable1);

        jButton5.setFont(new java.awt.Font("Swis721 Cn BT", 0, 30)); // NOI18N
        jButton5.setText("CARI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Swis721 Cn BT", 0, 36)); // NOI18N
        jButton6.setText("REFRESH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        jTabbedPane1.addTab("STOK", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 728));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\Clothing_Distro\\GUI.JPG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(JOptionPane.showConfirmDialog(null, "APAKAH ANDA YAKIN UNTUK LOGOUT","PERINGATAN", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            home l=new home();
            l.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Object header[]={"ID BARANG","NAMA BARANG","STOK","HARGA"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        jTable1.setModel(data);
        setKoneksi();
        String sql="Select * from barang";
        try {
            ResultSet rs=st.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString(1);
                String kolom2=rs.getString(2);
                String kolom3=rs.getString(3);
                String kolom4=rs.getString(4);
                String kolom[]={kolom1,kolom2,kolom3,kolom4};
                data.addRow(kolom);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String cari = JOptionPane.showInputDialog(null, "ID BARANG", "Input", JOptionPane.QUESTION_MESSAGE);
        Object header[]={"ID BARANG","NAMA BARANG","STOK","HARGA"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        jTable1.setModel(data);
        setKoneksi();
        String sql="Select * from barang where id_barang like '%" + cari +"%'";
        try {
            ResultSet rs=st.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString(1);
                String kolom2=rs.getString(2);
                String kolom3=rs.getString(3);
                String kolom4=rs.getString(4);
                String kolom[]={kolom1,kolom2,kolom3,kolom4};
                data.addRow(kolom);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        selesai();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    jTextField14.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
        j15.setText("");
    }//GEN-LAST:event_j15ActionPerformed

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        j14.setText("");
    }//GEN-LAST:event_j14ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
        j13.setText("");
    }//GEN-LAST:event_j13ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
        j12.setText("");
    }//GEN-LAST:event_j12ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        j11.setText("");
    }//GEN-LAST:event_j11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        area.setText("***********************************************************\n");
        area.setText(area.getText()+"                       CLOTHING DISTRO                     \n");
        area.setText(area.getText()+"***********************************************************\n");
        Date obj = new Date();
        String date = obj.toString();
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(jDateChooser1.getDate()));
        area.setText(area.getText()+"\n"+date+"\n\n");
        area.setText(area.getText()+"ID PEMESANAN\t: "+j1.getText()+"\n");
        area.setText(area.getText()+"NAMA PEMESAN\t: "+j2.getText()+"\n");
        area.setText(area.getText()+"NO HP\t\t: "+j3.getText()+"\n");
        area.setText(area.getText()+"ALAMAT\t\t: "+j4.getText()+"\n");
        area.setText(area.getText()+"JENIS KAIN\t\t: "+j5.getText()+"\n");
        area.setText(area.getText()+"WARNA\t\t: "+j6.getText()+"\n");
        area.setText(area.getText()+"JENIS SABLON\t: "+j7.getText()+"\n");
        area.setText(area.getText()+"JUMLAH\t\t: "+j8.getText()+"\n");
        area.setText(area.getText()+"HARGA\t\t: "+jTextField14.getText()+"\n");
        area.setText(area.getText()+"TANGGAL PENGAMBILAN\t: "+tanggal+"\n");
        area.setText(area.getText()+"SIZE\tS\t: "+j10.getText()+"\n");
        area.setText(area.getText()+"\tM\t: "+j11.getText());
        area.setText(area.getText()+"\n\tL\t: "+j12.getText());
        area.setText(area.getText()+"\n\tXL\t: "+j13.getText());
        area.setText(area.getText()+"\n\tXXL\t: "+j14.getText());
        area.setText(area.getText()+"\n\tLAIN\t: "+j15.getText()+"\n");
        area.setText(area.getText()+"\n\tJEMBER");

        try{
            area.print();
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Tambah();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        j8.setText("");
    }//GEN-LAST:event_j8ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        j7.setText("");
    }//GEN-LAST:event_j7ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        j6.setText("");
    }//GEN-LAST:event_j6ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        j5.setText("");
    }//GEN-LAST:event_j5ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        j4.setText("");
    }//GEN-LAST:event_j4ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        j3.setText("");
    }//GEN-LAST:event_j3ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        j2.setText("");
    }//GEN-LAST:event_j2ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        j1.setText("");
    }//GEN-LAST:event_j1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KARYAWAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j8;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField14;
    // End of variables declaration//GEN-END:variables

void Tambah()
{   
    String tampilan = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
    String tanggal = String.valueOf(fm.format(jDateChooser1.getDate()));
    try
    {
        Koneksi ObjKoneksi = new Koneksi();
        Connection con = ObjKoneksi.bukaKoneksi();
            Statement st = con.createStatement();
            //tempat data ditambahkan
            String sql = "insert into pesan values ('"+j1.getText()+
                    "','"+j2.getText()+
                    "','"+j3.getText()+
                    "','"+j4.getText()+
                    "','"+j5.getText()+
                    "','"+j6.getText()+
                    "','"+j7.getText()+
                    "','"+j8.getText()+
                    "','"+tanggal+
                    "','"+j10.getText()+
                    "','"+j11.getText()+
                    "','"+j12.getText()+
                    "','"+j13.getText()+
                    "','"+j14.getText()+
                    "','"+j15.getText()+
                    "','"+jTextField14.getText()+"')";
            
            int row = st.executeUpdate(sql);
            
            //pesan jika data sukses ditambahkan
            if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
                
                con.close();
            }
        }
        //data gagal dimasukkan pada database
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data tidak ditambahkan ke" +
                    " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
        }
}
void selesai()
{   
    String tampilan = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
    String tanggal = String.valueOf(fm.format(jDateChooser1.getDate()));
    try
    {
        Koneksi ObjKoneksi = new Koneksi();
        Connection con = ObjKoneksi.bukaKoneksi();
            Statement st = con.createStatement();
            //tempat data ditambahkan
            String sql = "insert into selesai values ('"+j1.getText()+
                    "','"+j2.getText()+
                    "','"+j3.getText()+
                    "','"+j4.getText()+
                    "','"+j5.getText()+
                    "','"+j6.getText()+
                    "','"+j7.getText()+
                    "','"+j8.getText()+
                    "','"+tanggal+
                    "','"+j10.getText()+
                    "','"+j11.getText()+
                    "','"+j12.getText()+
                    "','"+j13.getText()+
                    "','"+j14.getText()+
                    "','"+j15.getText()+"')";
            
            int row = st.executeUpdate(sql);
            
            //pesan jika data sukses ditambahkan
            if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
                
                con.close();
            }
        }
        //data gagal dimasukkan pada database
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data tidak ditambahkan ke" +
                    " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
        }
    try
    {
        Koneksi ObjKoneksi = new Koneksi();
        Connection con = ObjKoneksi.bukaKoneksi();
        Statement st = con.createStatement();
        //perintah untuk menghapus data
        String sql = "delete from pesan where id_pesanan = '"+j1.getText()+"' ";
        int row = st.executeUpdate(sql);
        //data berhasil dihapus
    }
    //data gagal dihapus
    catch(SQLException e)
    {
    }
}
public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/sablon?serverTimezone=UTC","root","");
            st=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
}
